#pragma config(Sensor, port8,  ,               sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port9,  ,               sensorVexIQ_ColorHue)
#pragma config(Sensor, port10, ,               sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor7,           ,             tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor12,          ,             tmotorVexIQ, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int T_Break = 100;
int global_color = 0;
int col[10];
int Eold = 0;

void pid(float KP, float KD, int V){
	int E = (getColorGrayscale(port10) - getColorGrayscale(port8));
	int P = E * KP;
	int D = KD * (E - Eold);
	int U = P + D;
	int speedleft = V+U;
	int speedright = V-U;
	if (speedleft > 100){speedleft = 100;}
	if (speedright > 100){speedright = 100;}
	setMotorSpeed(motor7, speedright);
	setMotorSpeed(motor12, speedleft);
	E = Eold;
}
void go(int L, int R){
	setMotorSpeed(motor7, R);
	setMotorSpeed(motor12, L);
}

void forward() {
	while (getColorGrayscale(port10) > 330 || getColorGrayscale(port8) > 330) {
		pid(0.11345, 0.046, 85);
	}
	go(40, 40);
	delay(400);
	go(0, 0);
	delay(T_Break);
}
void left() {
	go(-60, 60);
	delay(150);
	while (getColorGrayscale(port10) > 300)
		go(-60, 60);
	delay(120);
	go(0, 0);
	delay(T_Break);
}
void right() {
	go(60, -60);
	delay(150);
	while (getColorGrayscale(port8) > 300)
		go(60, -60);
	delay(120);
	go(0, 0);
	delay(T_Break);
}
void around(){
	right();
	right();
}
void finish(){
	go(50, 50);
	delay(700);
	go(0, 0);
}
void getcolor(){
	if(getColorHue(port9)>240 || getColorHue(port9)<15){global_color = 1;}
	if(getColorHue(port9)>30 && getColorHue(port9)<60){global_color = 2;}
	if(getColorHue(port9)>=160 && getColorHue(port9)<173){global_color = 3;}
	if(getColorHue(port9)>140 && getColorHue(port9)<159){global_color = 0;}
	char qwe[] = "-RYB";
	displayTextLine(2, "%d", getColorHue(port9));
}
task main()
{
	resetMotorEncoder(motor7);
	resetMotorEncoder(motor12);
	setMotorTarget(motor7, 165, 30);
	setMotorTarget(motor12, 165, 30);
	waitUntilMotorStop(motor7);
	waitUntilMotorStop(motor12);
	delay(90);
	for(int i = 0; i<10; i++){
		getcolor();
		col[i] = global_color;
		resetMotorEncoder(motor7);
		resetMotorEncoder(motor12);
		setMotorTarget(motor7, 85, 30);
		setMotorTarget(motor12, 85, 30);
		waitUntilMotorStop(motor7);
		waitUntilMotorStop(motor12);
		delay(200);
	}
	forward();
	playSound(soundHeadlightsOn);
	for(int i = 0; i<10; i++){
		if(col[i] == 1){around();}
		if(col[i] == 2){left();}
		if(col[i] == 3){right();}
		forward();
		playSound(soundHeadlightsOn);
	}
	for(int i = 0; i<=2; i++){
		playSound(soundWrongWay);}
	around();
	forward();
	around();
	forward();
	around();
	for(int i = 9; i>=0; i--){
		forward();
		if(col[i] == 1){around();}
		if(col[i] == 2){right();}
		if(col[i] == 3){left();}
		playSound(soundHeadlightsOn);
	}
	forward();
	resetMotorEncoder(motor7);
	resetMotorEncoder(motor12);
	setMotorTarget(motor7, 250, 50);
	setMotorTarget(motor12, 250, 50);
	waitUntilMotorStop(motor7);
	waitUntilMotorStop(motor12);
	resetMotorEncoder(motor7);
	resetMotorEncoder(motor12);
	setMotorTarget(motor7, 100, 50);
	setMotorTarget(motor12, -100, 50);
	waitUntilMotorStop(motor7);
	waitUntilMotorStop(motor12);
}
