#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
	int r = 0;
	int g = 0;
	int b = 0;
	//displayTextLine(7, "%d", SensorValue[S1]);
	wait1Msec(100);
	getColorRGB(S1, r, g, b);
	displayTextLine(9, "%d %d %d", r, g, b);



}
}
