#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Touch, modeEV3Bump)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	resetBumpedValue(S2);
	while(1){
	displayBigTextLine(7, "%d", SensorValue[S2])
}
}
