#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Touch)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		displayBigTextline(4, "distance - %d", getUSDistance(S1));
		displayBigTextline(6, "zone - %d", (getUSDistance(S1) - 8) - in_min) * (out_max - out_min) / (in_max - in_min) + out_min);

		if(getUSDistance(S1) < 70 && getUSDistance(S1) >8){
			setMotorSpeed(motorA, (getUSDistance(S1) - 8) * (255 - 0) / (70 - 8) + 0);


	}else{setMotorSpeed(motorA, 0);}

	}

}
