#pragma config(Sensor, S1,     ,               sensorEV3_Ultrasonic)
#pragma config(Sensor, S2,     ,               sensorEV3_Touch)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1){
		int zon = getUSDistance(S1)/50;
		displayBigTextline(4, "distance - %d", getUSDistance(S1));
		displayBigTextline(6, "zone - %d", getUSDistance(S1)/50);
    if(zon == 0){setMotorTarget(motorA, 0, 100);waitUntilMotorStop(motorA);}
    if(zon == 1){setMotorTarget(motorA, 60, 100);waitUntilMotorStop(motorA);}
    if(zon == 2){setMotorTarget(motorA, 120, 100);waitUntilMotorStop(motorA);}
    if(zon == 3){setMotorTarget(motorA, 180, 100);waitUntilMotorStop(motorA);}
    if(zon == 4){setMotorTarget(motorA, 240, 100);waitUntilMotorStop(motorA);}
    if(zon == 5){setMotorTarget(motorA, 300, 100);waitUntilMotorStop(motorA);}
    }

}
